- name: install nginx
  yum: 
    name:
      - nginx
    state: latest
    update_cache: yes
  become: yes
  become_user: vagrant
  become_method: sudo

- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

