- name: install nginx
  yum:
    name:
      - nginx
      - postgresql
      - postgresql-server     
    state: present

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: index
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
