---
- name: "Installation Using Docker"
  hosts: prod
  become: yes
  remote_user: codellya
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_user: codellya
  pre_tasks:
    - name: Installation de quelques packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - wget
        - git
    - name: Installation de python-pip
      yum:
        name: python3-pip
        state: present
        update_cache: yes
    - name: "Install docker python"
      pip:
        name: docker-py
  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /root/httpdvolume/index.html
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
    - name: Pull a Docker Image
      docker_image:
        name: httpd
        tag: latest
        source: pull
      register: z
    - name: Checking Pull Status
      debug:
        var: z
    - name: Creating a Persistent Volume
      file:
        path: "/root/httpdvolume"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Create Apache conteneur
      docker_container:
        name: webapp
        image: httpd
        state: started
        detach: true
        interactive: true
        ports:
          - "8181:80"
        volumes:
          - /root/httpdvolume/index.html:/usr/local/apache2/htdocs/index.html
