all: 
  vars:
    ansible_connection: ssh
    ansible_user: codellya 
    env: "environnement de formation"
prod: 
  hosts:
    worker1:
      ansible_host: 192.168.2.17
    worker2:
      ansible_host: 192.168.2.18

bdd: 
  hosts:
    master:
      ansible_host: 192.168.2.16

