---
ha:
  hosts:
    master:
  vars:
#    ha_config=/home/vagrant/haproxy.cfg

web:
  hosts:
    worker1:
    worker2:
  vars:
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_become: yes
    ansible_python_interpreter: "/usr/lib/python3.6"
