web: # keys must be unique, i.e. only one 'hosts' per group
  hosts:
    worker1:
      ansible_host: 192.168.2.17
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_become: yes
      ansible_become_method: enable
    worker2:
      ansible_host: 192.168.2.18

      
    