web: 
  hosts:
    worker1:
      ansible_host: 192.168.2.17
      ansible_connection: ssh
      ansible_user: codellya
      ansible_become: yes
      ansible_become_method: sudo
    worker2:
      ansible_host: 192.168.2.18
      ansible_connection: ssh
      ansible_user: codellya
      ansible_become: yes
      ansible_become_method: sudo
      
    